# -*- coding: utf-8 -*-
"""Onsite Practice -2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKJrJbgIntlLr3J148YckIBuBpy_WlQy
"""

import os
name = None
score = None
search = None
data = {}

while (name != ''):
    name = input('Please input name:')
    if (name == ''):
        break
    score = input('Please input score:')
    if (score != ''):
        data[name] = score
        #print(data)

names = list(data.keys())
scores = list(data.values())

"""
while (search != ''):
    search = input('Please input search:')
    if (search != ''):
        print(data.get(search,"unfind"))
"""


for i in range(len(data)):
    print("Student '{}' has a score of {}".format(names[i],scores[i]))

"""
for key,value in data.items():
    print("Student '{}' has a score of {}".format(key,value))
"""
print("Progame trminated!")
os.system("pause")