# -*- coding: utf-8 -*-
"""Onsite Practice (Individually)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/170cFn6VBH-yOxXZ2qTj5_cPNhV1wOQ_a
"""

def T(a,b,s):
    if (a == b):
        return s
    elif (a=='a' and b=='b'):
        return s * 0.01
    elif (a=='b' and b=='a'):
        return s * 100
    elif (a=='c' and b=='d'):
        return (s-32) * 5 /9
    elif (a=='d' and b=='c'):
        return s * (9/5) + 32
    else :
        return 'Error'

def D():
    a = input('選擇來源進制 a)公分 b)公尺 c)攝氏 d)華氏:')
    while (ord(a)<97 and 100>ord(a)):
        a = input('重新選擇來源進制 a)公分 b)公尺 c)攝氏 d)華氏:')

    b = input('選擇目標進制 a)公分 b)公尺 c)攝氏 d)華氏:')
    while ((ord(b)<97 and 100>ord(b)) or ((a=='a' or a=='b') and (b=='c' or b=='d')) or ((a=='c' or a=='d') and (b=='a' or b=='b'))):
        b = input('重新選擇目標進制 a)公分 b)公尺 c)攝氏 d)華氏:')
            
    return a,b

f = int(input('選單 (1)進制轉換 (2)離開程式:'))
while (f != 2):
    a,b = D()
    s = int(input('請輸入欲轉換的值:'))
    t = T(a,b,s)
    print('轉換後的值為:',t)
    f = int(input('選單 (1)進制轉換 (2)離開程式:'))
print('結束')