# -*- coding: utf-8 -*-
"""Onsite Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1prXbzfi1iW-HWVCv95jEx2PrYd_ty7iP
"""

deposit = float(input('Please input your deposit:'))
print('6 years later.Your deposit will be %f' %(deposit*(1+0.02)**6))