# -*- coding: utf-8 -*-
"""Onsite practice-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lw92CeajurgCd0C47XEgznv1rpONHkTf
"""

print('姓名\t學號\t國文\t英文\t數學')
print('吳明軒\t%3d\t%3d\t%3d\t%3d'%(12,100,100,100))
print('林暐峻\t%3d\t%3d\t%3d\t%3d'%(22,50,50,50))
print('柯昆霖\t%3d\t%3d\t%3d\t%3d'%(36,50,50,50))
print('蔡承恩\t%3d\t%3d\t%3d\t%3d'%(50,0,0,0))