# -*- coding: utf-8 -*-
"""Onsite practice-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_e2fQgtBovUQHjSTUbemWSf67s7aidii
"""

score1 = int(input('Please input your score1 score:'))
score2 = int(input('Please input your score2 score:'))
score3 = int(input('Please input your score3 score:'))
print('Your total sccor is %d' %(score1+score2+score3))