# -*- coding: utf-8 -*-
"""Onsite Practice 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvxq6NtSEb_nSaHherNmqUWfg8Myrom2
"""

import os
subjects = ['Chinese','English','Math   ']
scores = []
for i in range(len(subjects)):
    scores.append(int(input('Please input a score:')))
for i in range(len(subjects)):
    print('subject:', subjects[i],'score:', scores[i])
os.system("pause")