# -*- coding: utf-8 -*-
"""Onsite Practice 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvxq6NtSEb_nSaHherNmqUWfg8Myrom2
"""

import os
subjects = ['Chinese','English','Math   ']
scores = [80,90,100]
print('subject:', subjects[0],'score:', scores[0])
print('subject:', subjects[1],'score:', scores[1])
print('subject:', subjects[2],'score:', scores[2])
os.system("pause")