# -*- coding: utf-8 -*-
"""Onsite Practice 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvxq6NtSEb_nSaHherNmqUWfg8Myrom2
"""

import os

def sum(scores):
    sum = 0
    for score in scores:
        sum += score
    return sum

def average(scores, sum):
    average = sum/len(scores)
    return average
    
scores = []
score = int(input('Please input a score:'))

while(score != -1):
    scores.append(score)
    score = int(input('Please input a score:'))

print('sum of scores = ',sum(scores))
print('average of scores = ',average(scores, sum(scores)))

os.system("pause")