# -*- coding: utf-8 -*-
"""Onsite Practice 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvxq6NtSEb_nSaHherNmqUWfg8Myrom2
"""

import os
files = ['吳明軒',10856012,True]
for file in files:
    print(file)
os.system("pause")