# -*- coding: utf-8 -*-
"""Onsite_practice_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sARGzfBdWlQ6DitCvUlCPCW6dJjLENO8
"""

password = input('Please input a password:')
print('Welcome to NPUST!!' if password=='69115908' else 'Password ERROR!!')