# -*- coding: utf-8 -*-
"""Onsite_practice_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s3Ed59DJgFlv2y_f7QuMEAmcp96isMR_
"""

password = input('Please input a password:')
print('歡迎光臨 NPUST' if password=='69115908' else '')