# -*- coding: utf-8 -*-
"""Onsite practice 2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tpYMOjzyS92S7s_Eozr2iHknPQL_hZ1R
"""

import os
cost = input('請輸入消費金額:')
while(not isinstance(cost,int)):#如果金額不為整數型態，就不斷執行。
    cost = int(cost) if cost.isdigit() else input('請重新輸入消費金額:')#註解在下方
    """
    if(cost.isdigit()):#如果金額變數資料皆為數值型態則執行
        cost = int(cost)#將金額強制轉型為整數型態
    else:#如果金額變數資料不完全為數值型態則執行
        cost = input('請重新輸入消費金額:')#請重新輸入消費金額
    """
cost *= 0.8 if cost>=100000 else 0.85 if cost>=50000 else 0.9 if cost>=30000 else 0.95 if cost>=10000 else 1 #註解在下方
"""
if(cost>=100000): #如果消費金額在100000以上
    cost*=0.8 #就打8折
elif(cost>=50000): #如果消費金額在50000以上
    cost*=0.85 #就打85折
elif(cost>=30000): #如果消費金額在30000以上
    cost*=0.9 #就打9折
elif(cost>=10000): #如果消費金額在10000以上
    cost*=0.95 #就打95折
else:       #如果消費金額在10000以下
    cost*=1  #就不打折
"""

print('折扣後消費金額:{}'.format(cost))#顯示折扣後的消費金額
os.system("pause");