# -*- coding: utf-8 -*-
"""Onsite_practice_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R52lQqYb0oGqG5tatJhMugbEw1Di-MFD
"""

score = int(input('Please input a score:'))
"""
if(score>=90):
    print('S Class')
elif(score>=80):
    print('A Class')
elif(score>=70):
    print('B Class')
elif(score>=60):
    print('C Class')
else:
    print('D Class,Fail!')
"""
print('S Class' if score>=90 else 'A Class' if score>=80 else 'B Class' if score>=70 else 'C Class' if score>=60 else 'D Class,Fail!' )