# -*- coding: utf-8 -*-
"""Onsite Practice - 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VHjKj7Ku3MpB_uiGNIFnIY9mrUlk6v_K
"""

import os
start = int(input('Please input a start value:'))
stop = int(input('Please input a stop value:'))
step = int(input('Please input a step value:'))
sum=0
for i in range(start,stop,step):
    print(i,end='#')
    sum+=i
print(' Sum of sequence=',sum)

os.system('Pause')