# -*- coding: utf-8 -*-
"""Onsite Practice - 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VHjKj7Ku3MpB_uiGNIFnIY9mrUlk6v_K
"""

import os

for Multiplicand in range(1,10):
    for Multiplier in range(1,10):
        print('%d*%d=%2d'%(Multiplicand,Multiplier,Multiplicand*Multiplier),end='\t')
    print("")

os.system('Pause')