# -*- coding: utf-8 -*-
"""Onsite Practice - 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VHjKj7Ku3MpB_uiGNIFnIY9mrUlk6v_K
"""

import os

A = int(input('Please input number1:'))
B = int(input('Please input number2:'))

def GCD(n,m):
    return m if n%m==0 else GCD(m,n%m)
    """
    if n%m==0:
        return m
    else:
        return GCD(m,n%m)
    """
def LCM(n,m):
    return n*m/GCD(n,m)

print('Find GCD(A,B)=',GCD(A,B))
print('Find LCM(A,B)=',LCM(A,B))

os.system('Pause')